version: '3.9.7'
services:
  isleofcars:
    build: ./isleofcars
    container_name: isleofcars
    volumes:
      - ./isleofcars:/app
    ports:
      - "127.0.0.1:8080:8080"
    restart: always
    networks:
      - wcw
networks:
  wcw:
    external: true
    driver: bridge
