name: github-action-deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          script: | 
            whoami
            cd /mnt/wholecars-web
            git pull origin main 
            docker-compose down
            docker-compose up -d --build  
      
